package com.Exception;

public class ExceptionDemo1 {

    public static void main(String[] args) {
//        int [] arr = {1,23,6,4,9,};
//        System.out.println(arr[10]);   // 当代码出现了异常,那么就在这里创建了一个异常对象.
//                                       //  new  ArrayIndexOutBoundExceptionn();


        float a3 = 1.2f;
        double b2 = 1.5;
        float a2 = '1';
        System.out.println(a2);





     }
}
